### ISSUE TITLE
franka.mjb file is not uploaded!!!

### ISSUE THREAD

**Issue by githubs-user** [peterdavidfagan/mujoco_ros_sim#1]
Thanks for all the work that goes into this repository, it seems to be a nice project, but the franka.mjb file does not exist and so cannot be loaded. If I may, share this file or help how to run this package with a .xml or .urdf file.

**Comment by peterdavidfagan** [comment]
Hi @githubs-user, 

> Thanks for all the work that goes into this repository, it seems to be a nice project.

Thank you.

> the franka.mjb file does not exist and so cannot be loaded. If I may, share this file or help how to run this package with a .xml or .urdf file.

I made the decision to change the naming of the simulation files, for instance the current shipped file is `rearrangement_env.mjb` as seen [here](https://github.com/peterdavidfagan/mujoco_ros/tree/main/models). The launch script references this file for launching the simulation instance [here](https://github.com/peterdavidfagan/mujoco_ros/blob/main/launch/mjsim.launch.py).

I thought about naming the env files to align with the environment script name (e.g. franka.cpp for implementation and franka.mjb for sim file). In previous commits you will see that this is the case, however, since the implementation files only handles the interface between robots and ros2_control and not environment scene props etc. I decided to break this pattern. The reasoning being that for one implementation file I may have various scene descriptions with different configurations of props. 

As the package gets more mature, I plan to add support for prop information and tutorials but the package isn't at this level of maturity just yet. 

Please feel free to continue to open issues/ask questions as I am happy to address these.

**Comment by MarySeraj** [comment]
Thank you for your reply. I asked this question because in line 9 of the franka implementation file [here](https://github.com/peterdavidfagan/mujoco_ros/blob/main/src/franka.cpp) refers to the "franka.mjb":

`this->declare_parameter("model_file", "./models/franka.mjb");`

and running the franka.cpp file results in this error:
```
ros2 run mujoco_ros franka
WARNING: mju_openResource: unknown file './models/franka.mjb'
ERROR: Load model error: Could not load binary model
Press Enter to exit ...
```

**Comment by githubs-user** [comment]
Thank you for your reply. I asked this question because in line 9 of the mujoco_ros.cpp implementation file [here](https://github.com/peterdavidfagan/mujoco_ros/blob/main/src/mujoco_ros.cpp) refers to the "franka.mjb":

`this->declare_parameter("model_file", "./models/franka.mjb");`

and running the franka.cpp file results in this error:
```
ros2 run mujoco_ros franka
WARNING: mju_openResource: unknown file './models/franka.mjb'
ERROR: Load model error: Could not load binary model
Press Enter to exit ...
```

**Comment by peterdavidfagan** [comment]
Ah ok I see, this is the default parameter value, it gets overwritten by the parameter in the launch argument script. To avoid confusion I will default to empty string as this default should not work, my apologies about this. 

I'll test this change and close the issue once this has been pushed.

**Comment by githubs-user** [comment]
Thanks @peterdavidfagan. Could you also share the source of the XML or URDF of your "rearrangement_env.mjb" file to see how your implementation works?

**Comment by peterdavidfagan** [comment]
> Thanks @peterdavidfagan. Could you also share the source of the XML or URDF of your "rearrangement_env.mjb" file to see how your implementation works?

I plan to open source the repository for this, the current repository from which I generate this code contains code for a research project so I cannot open source until this work is published. If I get the time I will try to create a mirror repository with the research code removed.

The setup I have allows for dynamically changing actuators etc. so I'll be sure to share once ready. For now I will make the `mujoco_ros` package more stable, happy to answer questions about the shipped environments.

**Comment by githubs-user** [comment]
Thanks for your response. I asked you to share the XML file just to know how should I replace my XML instead of yours. so, if sharing your XML file is impossible, please tell me how I can use my XML or URDF file instead of your binary model.

**Comment by peterdavidfagan** [comment]
>  I asked you to share the XML file just to know how should I replace my XML instead of yours.

I would reference the MuJoCo xmls as my scenes are basic variations on this. You can find the base scene for the Franka [here](https://github.com/google-deepmind/mujoco_menagerie/blob/main/franka_emika_panda/scene.xml). 

> please tell me how I can use my XML or URDF file instead of your binary model.

You can include your xml file in the model directory and build the package. Then you need to reference this xml file in your launch script as a parameter. I intend to add tutorials for this to the following [site](https://peterdavidfagan.com/ros2_robotics_research_toolkit/) but it will take another while before this is available.

**Comment by peterdavidfagan** [comment]
@githubs-user what alterations are you trying to make to the sim environment? I can generate a zip with xml + assets but only want to do so if it is useful to you for a given reason. The example in mujoco menagerie is very similar to what I would share.

**Comment by peterdavidfagan** [comment]
Resolved original question through fixing default param value: e42f457fda596bc3e18d02ce5c8c84c0ee7688e2
